### ISSUE TITLE
main.js crash without error message when generating images

### ISSUE THREAD

**Issue by svher** [mateogianolio/mlp-character-recognition#11]
I found main.js always exit when loop to 32
```
for(index = 0; index < samples; index++)
  {
  	captcha.generate(settings, generate,index);
  	console.log(index);
  }
```
My operation system is Windows 10.

**Comment by svher** [comment]
This is my config file
```
{
  "mnist": false,
  "text": "0123456789",
  "fonts": [
    "sans-serif",
    "serif"
  ],
  "training_set": 100,
  "testing_set": 50,
  "image_size": 16,
  "threshold": 400,
  "network": {
    "hidden": 40,
    "learning_rate": 0.1
  }
}
```
only works fine when change distortion to false.

**Comment by mateogianolio** [comment]
Thanks for reporting the issue @svhero658! Will check it out tonight 👍

**Comment by mateogianolio** [comment]
Have you followed all the steps in the [Windows installation guide for node-canvas](https://github.com/Automattic/node-canvas/wiki/Installation---Windows)? I'm on OSX and I can't reproduce the error and unfortunately cannot test on Windows at the moment.

**Comment by Dridjohnrose** [comment]
Hey Mateo, thanks for this, how would you tackle inputting an image into the network? Convert it to raw binary data first to be then passed to   predict()   as an array?

**Comment by mateogianolio** [comment]
Hey, you're welcome mate! Yeah I would suggest converting the image to BW and then (if necessary) applying some feature enhancing algorithm like [stroke-width transform [pdf]](http://cmp.felk.cvut.cz/~cernyad2/TextCaptchaPdf/Detecting%20Text%20in%20Natural%20Scenes%20with%20Stroke%20Width%20Transform.pdf) to improve the quality of prediction. I also think it helps to center the character in the image. Good luck!
