### ISSUE TITLE
Possible to train with own images

### ISSUE THREAD

**Issue by potmo** [mateogianolio/mlp-character-recognition#3]
I have a bunch of images with text in a specific font that I would like to OCR
Is it possible to create my own training data and how would one go about to do that?

**Comment by mateogianolio** [comment]
If you know the font in advance I would say the easiest way is to put that font in the config file (and tweak size, etc to your liking) and let the network train itself. See 'Configuration' and 'Usage' in the README.

Then you can use the trained network on your images, but you have to first convert them to a bit array of the size specified in the config file (see the functions parse and mnist in main.js for conversion examples).

Either way you probably have to write your own parsing function.

**Comment by potmo** [comment]
Great thanks. I'll try that out
