### ISSUE TITLE
How to use ocr.js

### ISSUE THREAD

**Issue by vellengs** [mateogianolio/mlp-character-recognition#6]
I added a test.js to load it, but I got the error: 

var ocr = require('./ocr.js');

/Users/xxxx/projects/ocr/mlp-character-recognition/ocr.js:1
(function (exports, require, module, __filename, __dirname) { function (input) {
                                                                       ^
The generated file is an anonymous function.

```
function (input) {
F = {
0: 0,
1: 0,
2: 0,
3: 0,
4: 0,
5: 0,
6: 0,
```

**Comment by vellengs** [comment]
By the way, the https://raw.githubusercontent.com/LearnBoost/node-canvas/master/install is  404 now

**Comment by mateogianolio** [comment]
Just add `module.exports =` in the beginning of ocr.js to use it with node.

Will push a fix for that and the 404 soon. If you're running OSX you can install cairo with `brew install cairo`.

**Comment by vellengs** [comment]
Hi mateogianolio,
Thank you for your reply.

I added the module.exports in the beginning of ocr.js, but it seems have no a method named "activate" yet.

```
var ocr = require('./ocr.js');
console.log(ocr.activate);   //echo undefined
```

Does my generated file not correct or should I convert it to synaptic.Architect.Perceptron manually?

I saw your code do the test by this way 

```
    network.train(perceptron, training, config.network.learning_rate);
    fs.writeFileSync('./ocr.js', perceptron.standalone().toString());
    network.test(perceptron, testing);
```

Can you make an example test using the orc.js that will be much clear.

**Comment by usherwong** [comment]
how to use ocr to recognise images, can u give a demo to show, import images & export the recognition

**Comment by mateogianolio** [comment]
Hey @vellengs and @usherwong, it took a while but I have now updated the code and the README with instructions. Also added a test file `test.js` that you can look at.

@usherwong If you have images of characters, you want to convert them to the format of the arrays you see in `test.js`).Then you should be able to use it as now shown in the README.

Hope it solved your issues.

**Comment by mateogianolio** [comment]
Somehow the usage instructions disappeared when I merged the PR, they are back up now :)

**Comment by mateogianolio** [comment]
Closing this now, if the problem persists please open a new issue.
